# Generated by Django 4.2.23 on 2025-07-30 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordenador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtor',
            options={'ordering': ['caf'], 'verbose_name': 'Produtor', 'verbose_name_plural': 'Produtores'},
        ),
        migrations.RemoveField(
            model_name='produtor',
            name='nome',
        ),
        migrations.AddField(
            model_name='produtor',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
