# Generated by Django 4.2.23 on 2025-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0002_alter_produtor_options_remove_produtor_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('produtor_nome', models.CharField(max_length=100)),
                ('trabalhadores', models.JSONField(blank=True, default=list)),
                ('produtos', models.JSONField(blank=True, default=list)),
                ('servicos', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-data'],
            },
        ),
    ]
