# Generated by Django 4.2.23 on 2025-08-01 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0003_servico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
