# Generated by Django 4.2.23 on 2025-08-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordenador', '0004_delete_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talhao',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='coordenador.terreno'),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrenos', to='coordenador.produtor'),
        ),
    ]
