version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://admin:senha123@mongodb:27017/agricola?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123
    ports:
      - "27277:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: